const es = {
  'lang':'es',
  'page':{
    'title':'Las Jordanas - Casa Rural',
    'maintitle_a':'Casa Rural',
    'godownbt':'Explorar',
    'godownbt_wait':'Cargando',
    'backtopbt':'Volver al título',
    'logo':'';
    'structure':[
      {
        'tab_name':'Bienvenidos',
        'tab_content':[
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
        ]
      },
      {
        'tab_name':'Galería',
        'tab_content':[
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
        ]
      },
      {
        'tab_name':'Información',
        'tab_content':[
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
        ]
      },
      {
        'tab_name':'Contacto',
        'tab_content':[
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
          {
            'section_name':'',
            'section_paragraphs':[
              ''
            ],
          },
        ]
      }
    ]
  }
}
